language: java
script:
  - ant compile
  - ant test
  - ant make
  - sudo apt-get install sshpass
  - sshpass -p "shabnam.996@gmail.com" scp -o StrictHostKeyChecking=no server.jar 94105803@198.144.184.34:/home/94105803/
  - sshpass -p "shabnam.996@gmail.com" scp -o StrictHostKeyChecking=no -r static/ 94105803@198.144.184.34:/home/94105803/
  - sshpass -p "shabnam.996@gmail.com" ssh 94105803@198.144.184.34 pkill java
  - sshpass -p "shabnam.996@gmail.com" ssh 94105803@198.144.184.34 "nohup java -jar /home/94105803/server.jar &"